### ISSUE TITLE
setup issue with C locale

### ISSUE THREAD

**Issue by wavexx** [firecat53/tabview#133]
Discovered while trying to make a package for python3:

```
% LANG=C python3 ./setup.py clean           
Traceback (most recent call last):
  File "./setup.py", line 13, in <module>
    long_description=open('README.rst').read(),
  File "/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 1165: ordinal not in range(128)
```

open() should specify the encoding, as it is known in this case.

**Comment by firecat53** [comment]
Try the fix in the 'develop' branch. Should work for python2 and python3. Thanks!

Scott
